#!/usr/bin/env perl
use App::Cope;
use App::Cope::Extra qw[percent_b];

my @headers = (
  '%Time',    'ExclSec', 'CumulS', '#Calls',
  'sec/call', 'Csec/c',  'Name',
);

sub process {
  if (/^%Time/) {
    for my $h (@headers) { mark $h => 'underline'; }
  }
  elsif (/Time =/) {
    line qr{Time = (.+)} => 'bold';
  }
  else {

    my $time = line qr{^\s*
		       (  [0-9.]+) \s+ # %Time
		       (-?[0-9.]*) \s+ # ExclSec
		       (-?[0-9.]+)     # CumulS
		    }x => \&{ percent_b 10, 20, 30 }, '', 'bold';

    if ($time or m/^\s{5,}/) {
      line qr{((?:\S+?::)*)(\S+)$} => 'blue', 'blue bold'; # name
    }

    line qr{\s(-)\s} => 'black bold';

  }
}

run( \&process, real_path, @ARGV );
