#!/usr/bin/env perl
use App::Cope;

my @headers = qw[total used free shared buffers cached];

sub process {
  if (/^\s+total/) {
    for my $h (@headers) { mark $h => 'underline'; }
  }
  else {
    line qr{^([^\d]+:)} => 'blue bold';
  }
}

run( \&process, real_path, @ARGV );
