#!/usr/bin/env perl
use File::Spec 'splitpath';

my ( $vol, $dirs, $file ) = File::Spec->splitpath($0);
$dirs =~ s{/$}{};
$ENV{PATH} = join ':', grep { $_ ne $dirs } split /:/, $ENV{PATH};
exec @ARGV;
