#!/usr/bin/env perl
use App::Cope;

# md5sum and its ilk output hashes. cache the hashes and highlight in
# bold if any of them matches another one.

my @colours = qw[green blue red yellow cyan magenta];
my %hashes;
my $i = 0;

sub process {
  if (/^([0-9a-f]{40})\s/) {
    if ( $1 eq "cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e" ) { # sha512sum("")
      return;  # ignore empty files
    }
    elsif ( $hashes{$1} ) {
      mark qr{^\S+} => "bold " . $hashes{$1};
    }
    else {
      $hashes{$1} = $colours[ $i++ % 6 ];
      mark qr{^\S+} => $hashes{$1};
    }
  }

  # checking output
  else {
    line qr{: (OK|FAILED)$} => { OK => 'green bold', FAILED => 'red bold' };
    line qr{sha512sum: (WARNING:) (\d+) (.+)} => 'white on_red', 'red bold', 'red';
  }

}

run( \&process, real_path, @ARGV );
