#!/usr/bin/env perl
use App::Cope;
use App::Cope::Extra qw[ping_time];
use Regexp::Common qw[net];

sub process {
  line qr{(\S+)\s\($RE{net}{IPv4}\)} => 'blue bold';
  line qr{(\(?$RE{net}{IPv4}\)?)}    => 'blue';
  line qr{^traceroute to (\S+)}      => 'blue bold underline';

  line qr{^\s*(\d+)		# trace number
	  \s+\d			# match first digit of IP, and avoid
                                # matching against the -v flag's
                                # output
       }x => 'bold';

  line qr{([0-9.]+ ms)\b} => \&ping_time;
  line qr{(\*)}           => 'red bold';
  line qr{ (![HNPSFX]?)}  => 'red';
}

run( \&process, real_path, @ARGV );
