#!/usr/bin/env perl
use App::Cope;
use Regexp::Common qw[net];

sub ping_time {
  my ($ms) = @_;
  $ms =~ s/ ms$//g;
  given ($ms) {
    when ( $_ >= 200 ) { return 'red bold' }
    when ( $_ >= 100 ) { return 'yellow bold' }
    default            { return 'green bold' }
  }
}

sub process {
  line qr{(\S+)\s(\($RE{net}{IPv4}\))} => 'blue bold', 'blue';
  line qr{\d+ bytes to ($RE{net}{IPv4})} => 'blue';
  line qr{^traceroute to (\S+)} => 'blue bold underline';

  line qr{^\s*(\d+)		# trace number
	  \s+\d			# match first digit of IP, and avoid
                                # matching against the -v flag's
                                # output
       }x => 'bold';

  line qr{([0-9.]+ ms)\b} => \&ping_time;
  line qr{(\*)}           => 'red bold';
  line qr{ (![HNPSFX]?)}  => 'red';
}

run( \&process, real_path, @ARGV );
